name: "Cloudflare AI Gateway Code Review Action"
description: "Perform code reviews and comment on diffs using OpenAI API."
inputs:
  GITHUB_TOKEN:
    description: "GitHub token to interact with the repository."
    required: true
  API_KEY:
    description: "API key for AI Gateway."
    required: true
  ENDPOINT_URL:
    description: "Endpoint URL for AI Gateway."
    required: true
  MODEL:
    description: "LLM model."
    required: false
    default: "@cf/meta/llama-3.1-8b-instruct-fast"
  exclude:
    description: "Glob patterns to exclude files from the diff analysis"
    required: false
    default: ""
runs:
  using: "node16"
  main: "dist/index.js"
branding:
  icon: "aperture"
  color: "green"
